### ISSUE TITLE
doesn't work with Samsung Smart TV

### ISSUE THREAD

**Issue by timikesmarky** [blackholeearth/Win10_BrightnessSlider#38]
Doesn't work on Smart TV. I'm looking for an app that controls Samsung TV brightness.

**Comment by blackholeearth** [comment]
if you are using hdmi cable . it probably cant  send Change Brightness Requests to smart tv. 
im not sure but probably only  vga , dvi works 

![Image of Yaktocat](http://oi64.tinypic.com/33a767l.jpg)


i was indecisive whether i should write  or not. cuz it may not fix this.

**Comment by timikesmarky** [comment]
Thanks for the comment. It's worth checking. I would buy an adapter to convert hdmi to vga if it does work.
I will have to check with a laptop with vga or dvi port. I'll update when I try it.

**Comment by blackholeearth** [comment]
sorry for misleading.  
here:https://en.wikipedia.org/wiki/HDMI
hdmi has has "pin 16"  ddc ci data. 
it still may not work with vga  cable,

its probably because  in your device management your monitor(display ) driver is generic pnp. it's general purpose driver.
you have to install real driver.

#### how to do it ( copied from  #32 ): 
 if it shows up _generic microsoft pnp monitor_, you definitely try to install monitor / graphic drivers both.
 i updated drivers on my old 2006 pc with **driver_booster_setup**.
 ( it felt like a fake app. but it worked.)
 delete updater later if it bothers you mind

its a smart tv. it may not have a  driver for windows.

**Comment by timikesmarky** [comment]
Oh I see. So, no driver = No brightness app can support it right?

I know about overlay dimming apps. I don't like those.
There is only two softwares that work for me. CareUEyes and Freemonitormanager.
These two apps use Gamma Ramp API. So, it's the closest thing to control brightness on TV as monitor.

**Comment by blackholeearth** [comment]
There is emoacht/monitarian. Try it. better project than this.  İ was gonna use that 1 year before. wasnt able to run .

 Recently tried again. Now it runs..

Maybe it works with that

**Comment by blackholeearth** [comment]
Try these maybe  they work

https://clickmonitorddc.bplaced.net/

Github (emoaht sth) / monitarian

**Comment by timikesmarky** [comment]
@blackholeearth I have tried all these apps. I have tried every single brightness app available. None of them work, just the two I mentioned which are not free.

I think Smart TV brightness can't be controlled via apps.
