### ISSUE TITLE
Where is the source code of latest version?

### ISSUE THREAD

**Issue by xelnaga64** [blackholeearth/Win10_BrightnessSlider#62]
I can download the exe files at https://github.com/blackholeearth/Win10_BrightnessSlider/releases but all the source codes belong to an old version.

**Comment by blackholeearth** [comment]
Readme.

**Comment by Venryx** [comment]
@blackholeearth It's your right, of course, to not share the source code for the newest versions if you don't want to.

That said, I don't really understand why you wouldn't want to...

Is it because you don't want people to fork the project, and leave you out of a new (potentially main) development loop? In that case, you could license it under the GPL, which would force forked versions to share any modifications they make to the source code, meaning you can keep your version up to date with any enhancements other people make.
