### ISSUE TITLE
Feature request: Add key bindings to increase or decrees brightness

### ISSUE THREAD

**Issue by flkflorin** [blackholeearth/Win10_BrightnessSlider#92]
It would be nice to have keys binding to increase or decrees brightness and also a key button for detect monitors.

Always after I put PC to sleep I have to press Detect monitors button in order to change the brightness, if I not do that the slider does not work.

Thank you for this great tool!!

**Comment by chrismaliszewski** [comment]
Not sure if that's even possible but it'd be great if special keyboard buttons could be used, not just the keys' combination. 
On my keyboard, I have two special keys that I don't use at all now but they could be used for the brightness change.

**Comment by meessour** [comment]
Being able to use the dedicated brightness buttons on your keyboard (what laptops usually have in their F keys) would be amazing! I have a keyboard which has these key integrated so it would work perfectly for me. I looked into Hardware Key Handling but i couldn't find a way to detect when a user presses one of these specific keys (of an API that works with JavaScript), but it looks like it only works for media controls like pause/play/forward/backward. I really hope this feature will become part of this app!

**Comment by blackholeearth** [comment]
@meessour  
os cant receive fn keys. only your computer bios can access it .  ie manufacturer ( samsung lenovo your pc brand ) they put a special dll  in their apllication to access  fn+up/down

**Comment by blackholeearth** [comment]
duplicate  of  #4

**Comment by meessour** [comment]
> @meessour
> os cant receive fn keys. only your computer bios can access it . ie manufacturer ( samsung lenovo your pc brand ) they put a special dll in their apllication to access fn+up/down

That is very disappointing...

**Comment by chrismaliszewski** [comment]
@blackholeearth, I don't think you're correct. One thing is, I have Clevo laptop with a fresh installation of Windows OS and I never installed any application from Clevo. Another proof comes straight from Wiki: 

> A function key is a key on a computer or terminal keyboard which can be programmed so as to cause **an operating system command interpreter** or application program to perform certain actions, a form of soft key.[1]

So the keyboard itself, I presume as you said with the help of BIOS, may run a function of OS.

**Comment by blackholeearth** [comment]
@chrismaliszewski  you have to figure out  how dll works. 

you have to do it for every brand.  maybe even models (much worse) .  its UNPRACTICAL..

**Comment by chrismaliszewski** [comment]
I can't agree with you; I think it's totally the other way around to what you suggest things are. 

Creators of OS create functions in their OS so others, i.e. software creators, can use them to do things in the OS. There is "but"; OS must work with as many devices/hardware as possible. So OS creators must come into agreement with major hardware manufacturers to a certain standard that will be used. In this way, both parties agree on the functions that must be implemented, what they will do and how they must be called from DLLs. 

Finally, hardware manufacturers create chips that according to the OS they detect, they send proper signals/call specific functions in the OS to perform what is needed. 

Since there are not that many OSes and the functions don't change much or at all, there is no problem with creating new hardware, i.e. keyboard, because each keyboard with a brightness key will call a function that is strictly specified for the OS that is running on a computer.

What you say would totally be unpractical.

At least, that is the way I see and find things around creating OS and hardware. Correct me if I'm wrong.

**Comment by blackholeearth** [comment]
@chrismaliszewski   i agree to that 100%.    FN KEY shoud have ALREADY been standard . (not vendor specific)

**Comment by chrismaliszewski** [comment]
Either I don't understand what you mean by "fn key should have already been a standard" or we're still not on the same page. 

Those are not the fn keys that need to standardise but functions in OS that are called by fn keys to do what they are supposed to because... functions that the fn keys call are not vendor based but OS based, in most of the cases. 

The only exceptions that I can think of are, either, badly designed keyboards that require additional apps or keyboards with tons of fn keys that have functions that require additional apps to run them. In every other case, a keyboard's chipset simply sends a signal to OS "run this function with these parameters", i.e. increase volume by 10 or decrease the brightness by 10 or shut down power or run an app called calc, etc.
